# Core Company & Product Tags
news:
  label: News
  permalink: /news
  description: Stay updated with the latest company news, product announcements, and important information from EchoDash - your real-time business events platform.

product-updates:
  label: Product Updates
  permalink: /product-updates
  description: Discover the latest features, improvements, and changes to the EchoDash platform. Keep up with our continuous development to maximize your business monitoring.

features:
  label: Features
  permalink: /features
  description: Detailed information about EchoDash features that help businesses track events, monitor activity, and streamline operations across multiple platforms.

echodash:
  label: EchoDash
  permalink: /echodash
  description: Everything you need to know about EchoDash - the real-time events platform that connects all your business tools in one unified dashboard.

# Technology & Integration Tags
integrations:
  label: Integrations
  permalink: /integrations
  description: Learn how EchoDash integrates with popular business tools like Slack, WordPress, and other platforms to create a unified monitoring experience.

dashboards:
  label: Dashboards
  permalink: /dashboards
  description: Comprehensive guides on creating effective dashboards for business monitoring, analytics, and performance tracking with EchoDash.

notifications:
  label: Notifications
  permalink: /notifications
  description: Everything about EchoDash's notification system - email digests, real-time alerts, and managing notification preferences to stay informed without overwhelm.

apis:
  label: APIs
  permalink: /apis
  description: Technical resources for developers working with EchoDash APIs, webhooks, and custom integrations for advanced business monitoring solutions.

# Business & Industry Tags
business-tools:
  label: Business Tools
  permalink: /business-tools
  description: Discover powerful applications, software, and tools that help businesses operate more efficiently and integrate with EchoDash for comprehensive monitoring.

small-business:
  label: Small Business
  permalink: /small-business
  description: Specialized content for small business owners looking to leverage technology and monitoring tools for better oversight, efficiency, and growth.

automation:
  label: Automation
  permalink: /automation
  description: Learn how to automate business processes, reduce manual work, and improve efficiency using EchoDash's monitoring capabilities and integrations.

analytics:
  label: Analytics
  permalink: /analytics
  description: Data analysis techniques, performance tracking, and business intelligence strategies to make better decisions with EchoDash's monitoring data.

# Product & Strategy Tags  
product-strategy:
  label: Product Strategy
  permalink: /product-strategy
  description: Strategic approaches to product planning, roadmapping, and execution, enhanced by EchoDash's real-time event monitoring and business intelligence.

product-development:
  label: Product Development
  permalink: /product-development
  description: Best practices and strategies for product development teams using EchoDash to track development milestones, user feedback, and performance metrics.

startup-strategy:
  label: Startup Strategy
  permalink: /startup-strategy
  description: Essential strategies for startups including product-market fit, lean methodology, and growth tactics enhanced by real-time business monitoring.

# Industry-Specific Tags
retail:
  label: Retail
  permalink: /retail
  description: Specialized solutions for retail businesses to monitor store performance, inventory changes, sales metrics, and customer interactions through EchoDash.

agencies:
  label: Agencies
  permalink: /agencies
  description: Resources and guides for agencies managing multiple client accounts, tracking project performance, and monitoring client website activity with EchoDash.

saas:
  label: SaaS
  permalink: /saas
  description: Software as a Service industry insights, best practices, and how SaaS companies can leverage EchoDash for product monitoring and customer success.

wordpress:
  label: WordPress
  permalink: /wordpress
  description: Comprehensive information about EchoDash's WordPress integration, monitoring WordPress sites, and managing multiple WordPress installations.

# Content Type Tags
guides:
  label: Guides
  permalink: /guides
  description: Step-by-step tutorials and comprehensive guides to help you get the most out of EchoDash and related business tools and strategies.

tutorials:
  label: Tutorials
  permalink: /tutorials
  description: Hands-on tutorials covering technical implementations, setup procedures, and practical applications of EchoDash features and integrations.

productivity:
  label: Productivity
  permalink: /productivity
  description: Tips, tools, and strategies to improve personal and team productivity, featuring apps and workflows that integrate with EchoDash monitoring.